### ISSUE TITLE
Add star wars elevator music

### ISSUE THREAD

**Issue by Shynixn** [Skinnerpuma737/ElevatorSymphony#1]
https://www.youtube.com/watch?v=c6zHyxHNcFg

**Comment by Skinnerpuma737** [comment]
# Response
Hi!
Thanks for downloading the mod.
I will not be adding the song however you can certainly add it yourself.
## Customizing Elevator Symphony
To add custom songs you follow the following steps:

1. Export your song in ogg, mp3 or wav format.

2. Navigate to the mod folder `Sk737-ElevatorSymphony`

3. Drag song into the `Music` folder.

---
Hopefully this clarifies the process to add your own songs. 

Regards
Skinnerpuma737
