### ISSUE TITLE
Add config setting to set the chance how often a Music track is played

### ISSUE THREAD

**Issue by Shynixn** [Skinnerpuma737/ElevatorSymphony#2]
e.g.

luigiElevator.ogg -> 20%
saffron.ogg -> 70%
myMusicTrack.ogg -> 10%
deadbirdstudio.ogg -> 0%
...

**Comment by Skinnerpuma737** [comment]
Thanks for the suggestion will look into this
---
Regards 
Skinnerpuma737

**Comment by Skinnerpuma737** [comment]
# Response
Feature is now implemented and has been uploaded to Thunderstore.
It may take a while for this change to be viewable on Thunderstore or the Mod Manager.

---

Regards 
Skinnerpuma737
